version: '3'
services:
  master:
    build:
      context: .
      dockerfile: ./manager.Dockerfile
    working_dir: /root/playbooks
    volumes:
      - /home/alphadi/ansible/playbooks:/root/playbooks
      - /home/alphadi/ansible/config:/etc/ansible
    command: tail -f /dev/null
    
  web:
    build:
      context: .
      dockerfile: ./nodes.Dockerfile

  db:
    build:
      context: .
      dockerfile: ./nodes.Dockerfile

  lb:
    build:
      context: .
      dockerfile: ./nodes.Dockerfile
    ports: 
    - 8080:80
